"""
glb_to_fbx.py
将 GLB 文件转换为 UE5 可用的 FBX ASCII 7.4 格式。

坐标系转换:
  GLTF  : Y-up, 右手系 (X=右, Y=上, Z=朝观察者)
  UE5   : Z-up, 左手系 (X=前, Y=右, Z=上)
  映射  : UE5_X=-GLTF_Z, UE5_Y=GLTF_X, UE5_Z=GLTF_Y
  比例  : ×100 (米 → 厘米)
  绕组  : 取反 Z 轴 → 镜像 → 翻转三角形绕组 (v0,v1,v2) → (v0,v2,v1)

用法:
    python glb_to_fbx.py level_test.glb
    python glb_to_fbx.py level_test.glb --out level_test.fbx
"""

import argparse
import io
import sys
import time
from pathlib import Path

# Fix Chinese print on Windows cp1252 consoles
if sys.stdout.encoding and sys.stdout.encoding.lower().startswith("cp"):
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

import numpy as np

try:
    import trimesh
except ImportError:
    raise SystemExit("pip install trimesh")


# ─── 坐标变换 ───────────────────────────────────────────────────

def gltf_to_ue5_vertices(verts: np.ndarray) -> np.ndarray:
    """
    GLTF (X,Y,Z) → UE5 (X,Y,Z) in centimeters.
      UE5.X = -GLTF.Z × 100
      UE5.Y =  GLTF.X × 100
      UE5.Z =  GLTF.Y × 100
    """
    out = np.empty_like(verts)
    out[:, 0] = -verts[:, 2] * 100.0   # UE5 X (forward) = -GLTF Z
    out[:, 1] =  verts[:, 0] * 100.0   # UE5 Y (right)   =  GLTF X
    out[:, 2] =  verts[:, 1] * 100.0   # UE5 Z (up)      =  GLTF Y
    return out


def gltf_to_ue5_normals(normals: np.ndarray) -> np.ndarray:
    """Same axis mapping as vertices, no scaling."""
    out = np.empty_like(normals)
    out[:, 0] = -normals[:, 2]
    out[:, 1] =  normals[:, 0]
    out[:, 2] =  normals[:, 1]
    return out


# ─── FBX 写入工具 ───────────────────────────────────────────────

def _fmt_floats(arr: np.ndarray, decimals: int = 6) -> str:
    """将 numpy 数组格式化为 FBX 紧凑列表。"""
    flat = arr.ravel()
    parts = []
    for v in flat:
        s = f"{v:.{decimals}f}"
        # 去掉不必要的尾零，但保留至少一位小数
        if '.' in s:
            s = s.rstrip('0').rstrip('.')
            if '.' not in s:
                s += '.0'
        parts.append(s)
    return ','.join(parts)


def _fmt_ints(arr: np.ndarray) -> str:
    return ','.join(str(int(v)) for v in arr.ravel())


def write_fbx(
    all_verts:  np.ndarray,   # (N, 3)  已变换到 UE5 坐标
    all_faces:  np.ndarray,   # (F, 3)  已翻转绕组
    all_normals: np.ndarray,  # (F*3, 3) 逐面顶点法线（已变换）
    all_colors:  np.ndarray,  # (F*3, 4) 逐面顶点颜色 float32 [0,1]
    output_path: str,
    source_file: str = "",
) -> None:
    geom_id  = 2_000_000_001
    model_id = 3_000_000_001
    doc_id   = 1_000_000_000

    n_verts  = len(all_verts)
    n_faces  = len(all_faces)
    n_pverts = n_faces * 3          # 每个三角形 3 个面顶点

    # FBX 多边形顶点索引: 负数表示多边形结束 → 最后一个索引取反 -(v+1)
    poly_idx = np.empty(n_pverts, dtype=np.int64)
    poly_idx[0::3] =  all_faces[:, 0]
    poly_idx[1::3] =  all_faces[:, 1]
    poly_idx[2::3] = -(all_faces[:, 2] + 1)   # 负号标记三角形终点

    t = time.localtime()
    ts = dict(year=t.tm_year, month=t.tm_mon, day=t.tm_mday,
              hour=t.tm_hour, minute=t.tm_min, second=t.tm_sec)

    lines = []
    W = lines.append   # shorthand

    # ── 文件头 ────────────────────────────────────────────────
    W("; FBX 7.4.0 project file")
    W(f"; Generated by LevelSmith glb_to_fbx.py from {source_file}")
    W("; UE5-compatible: Z-up, left-handed, centimeters")
    W("")
    W("FBXHeaderExtension:  {")
    W("    FBXHeaderVersion: 1003")
    W("    FBXVersion: 7400")
    W("    CreationTimeStamp:  {")
    W("        Version: 1000")
    for k, v in ts.items():
        W(f"        {k.capitalize()}: {v}")
    W("    }")
    W('    Creator: "LevelSmith"')
    W('    SceneInfo: "SceneInfo::GlobalInfo", "UserData" {')
    W('        Type: "UserData"')
    W("        Version: 100")
    W("        MetaData:  {")
    W("            Version: 100")
    W('            Title: ""')
    W('            Subject: ""')
    W('            Author: ""')
    W('            Keywords: ""')
    W('            Revision: ""')
    W('            Comment: "Exported by LevelSmith"')
    W("        }")
    W("    }")
    W("}")
    W("")

    # ── GlobalSettings (Z-up, cm) ────────────────────────────
    W("GlobalSettings:  {")
    W("    Version: 1000")
    W("    Properties70:  {")
    # UpAxis=2 → Z-up; FrontAxis=1 → Y-front; CoordAxis=0 → X-right
    W('        P: "UpAxis", "int", "Integer", "",2')
    W('        P: "UpAxisSign", "int", "Integer", "",1')
    W('        P: "FrontAxis", "int", "Integer", "",1')
    W('        P: "FrontAxisSign", "int", "Integer", "",-1')
    W('        P: "CoordAxis", "int", "Integer", "",0')
    W('        P: "CoordAxisSign", "int", "Integer", "",1')
    W('        P: "OriginalUpAxis", "int", "Integer", "",1')       # GLTF was Y-up
    W('        P: "OriginalUpAxisSign", "int", "Integer", "",1')
    W('        P: "UnitScaleFactor", "double", "Number", "",1')    # 1 = cm already
    W('        P: "OriginalUnitScaleFactor", "double", "Number", "",100')  # was 100cm/unit
    W('        P: "AmbientColor", "ColorRGB", "Color", "",0,0,0')
    W('        P: "DefaultCamera", "KString", "", "", "Producer Perspective"')
    W("    }")
    W("}")
    W("")

    # ── Documents ────────────────────────────────────────────
    W("Documents:  {")
    W("    Count: 1")
    W(f'    Document: {doc_id}, "", "Scene" {{')
    W("        RootNode: 0")
    W("    }")
    W("}")
    W("")
    W("References:  {")
    W("}")
    W("")

    # ── Definitions ──────────────────────────────────────────
    W("Definitions:  {")
    W("    Version: 100")
    W("    Count: 3")
    W("    ObjectType: \"GlobalSettings\" {")
    W("        Count: 1")
    W("    }")
    W("    ObjectType: \"Geometry\" {")
    W("        Count: 1")
    W('        PropertyTemplate: "FbxMesh" {')
    W("            Properties70:  {")
    W('                P: "Color", "ColorRGB", "Color", "",0.8,0.8,0.8')
    W('                P: "BBoxMin", "Vector3D", "Vector", "",0,0,0')
    W('                P: "BBoxMax", "Vector3D", "Vector", "",0,0,0')
    W("            }")
    W("        }")
    W("    }")
    W("    ObjectType: \"Model\" {")
    W("        Count: 1")
    W('        PropertyTemplate: "FbxNode" {')
    W("            Properties70:  {")
    W('                P: "InheritType", "enum", "", "",1')
    W('                P: "ScalingMax", "Vector3D", "Vector", "",0,0,0')
    W("            }")
    W("        }")
    W("    }")
    W("}")
    W("")

    # ── Objects ──────────────────────────────────────────────
    W("Objects:  {")

    # Geometry
    W(f'    Geometry: {geom_id}, "Geometry::LevelMesh", "Mesh" {{')
    W(f"        GeometryVersion: 124")

    W(f"        Vertices: *{n_verts * 3} {{")
    W(f"            a: {_fmt_floats(all_verts, 4)}")
    W("        }")

    W(f"        PolygonVertexIndex: *{n_pverts} {{")
    W(f"            a: {_fmt_ints(poly_idx)}")
    W("        }")

    # Normals (ByPolygonVertex)
    W("        LayerElementNormal: 0 {")
    W("            Version: 101")
    W('            Name: ""')
    W('            MappingInformationType: "ByPolygonVertex"')
    W('            ReferenceInformationType: "Direct"')
    W(f"            Normals: *{n_pverts * 3} {{")
    W(f"                a: {_fmt_floats(all_normals, 6)}")
    W("            }")
    W("        }")

    # Vertex Colors (ByPolygonVertex, Direct — no ColorIndex needed)
    W("        LayerElementColor: 0 {")
    W("            Version: 101")
    W('            Name: "Col"')
    W('            MappingInformationType: "ByPolygonVertex"')
    W('            ReferenceInformationType: "Direct"')
    W(f"            Colors: *{n_pverts * 4} {{")
    W(f"                a: {_fmt_floats(all_colors, 6)}")
    W("            }")
    W("        }")

    # Material (AllSame → single material slot)
    W("        LayerElementMaterial: 0 {")
    W("            Version: 101")
    W('            Name: ""')
    W('            MappingInformationType: "AllSame"')
    W('            ReferenceInformationType: "IndexToDirect"')
    W("            Materials: *1 {")
    W("                a: 0")
    W("            }")
    W("        }")

    # Layer 0
    W("        Layer: 0 {")
    W("            Version: 100")
    W("            LayerElement:  {")
    W('                Type: "LayerElementNormal"')
    W("                TypedIndex: 0")
    W("            }")
    W("            LayerElement:  {")
    W('                Type: "LayerElementColor"')
    W("                TypedIndex: 0")
    W("            }")
    W("            LayerElement:  {")
    W('                Type: "LayerElementMaterial"')
    W("                TypedIndex: 0")
    W("            }")
    W("        }")
    W("    }")   # end Geometry

    # Model
    W(f'    Model: {model_id}, "Model::LevelScene", "Mesh" {{')
    W("        Version: 232")
    W("        Properties70:  {")
    W('            P: "InheritType", "enum", "", "",1')
    W('            P: "ScalingMax", "Vector3D", "Vector", "",0,0,0')
    W('            P: "DefaultAttributeIndex", "int", "Integer", "",0')
    W("        }")
    W("        Shading: Y")
    W('        Culling: "CullingOff"')
    W("    }")   # end Model

    W("}")   # end Objects
    W("")

    # ── Connections ──────────────────────────────────────────
    W("Connections:  {")
    W(f"    C: \"OO\",{geom_id},{model_id}")
    W(f"    C: \"OO\",{model_id},0")
    W("}")
    W("")

    Path(output_path).write_text('\n'.join(lines), encoding='utf-8')


# ─── 主函数 ─────────────────────────────────────────────────────

def convert(glb_path: str, fbx_path: str) -> dict:
    print(f"[读取] {glb_path}")
    scene = trimesh.load(glb_path, force='scene')
    meshes = scene.dump(concatenate=False)
    print(f"  原始 mesh 数量: {len(meshes)}")

    # ── 修复法线 + 合并所有 mesh ───────────────────────────────
    vert_parts   = []
    face_parts   = []
    normal_parts = []
    color_parts  = []
    vert_offset  = 0
    fixed_normals = 0

    for m in meshes:
        # 修复法线方向：确保所有面法线朝外
        trimesh.repair.fix_normals(m, multibody=False)
        if not m.is_winding_consistent:
            trimesh.repair.fix_winding(m)
            fixed_normals += 1

        v  = m.vertices                                  # (V, 3) GLTF coords
        f  = m.faces                                     # (F, 3)
        fn = m.face_normals                              # (F, 3)

        # 面颜色 → RGBA float
        fc = m.visual.face_colors.astype(np.float32) / 255.0  # (F, 4)

        # 展开为逐面顶点 (F*3 rows)
        fn_pv = np.repeat(fn, 3, axis=0)          # (F*3, 3)
        fc_pv = np.repeat(fc, 3, axis=0)          # (F*3, 4)

        vert_parts.append(v)
        face_parts.append(f + vert_offset)
        normal_parts.append(fn_pv)
        color_parts.append(fc_pv)
        vert_offset += len(v)

    all_verts   = np.concatenate(vert_parts,  axis=0)
    all_faces   = np.concatenate(face_parts,  axis=0)
    all_normals = np.concatenate(normal_parts, axis=0)
    all_colors  = np.concatenate(color_parts,  axis=0)

    print(f"  顶点总数: {len(all_verts):,}  三角面: {len(all_faces):,}")
    if fixed_normals:
        print(f"  法线修复: {fixed_normals} 个 mesh")

    # ── 坐标变换 GLTF → UE5 ─────────────────────────────────
    ue5_verts   = gltf_to_ue5_vertices(all_verts)
    ue5_normals = gltf_to_ue5_normals(all_normals)

    # 坐标精度：round(4) 消除浮点误差
    ue5_verts   = np.round(ue5_verts,   4)
    ue5_normals = np.round(ue5_normals, 6)

    # 取反 Z 轴 → 镜像变换 → 翻转三角形绕组
    ue5_faces = all_faces[:, [0, 2, 1]]   # v0,v1,v2 → v0,v2,v1

    bbox = ue5_verts
    print(f"  UE5 坐标范围:")
    print(f"    X (前后): {bbox[:,0].min():.1f} ~ {bbox[:,0].max():.1f} cm")
    print(f"    Y (左右): {bbox[:,1].min():.1f} ~ {bbox[:,1].max():.1f} cm")
    print(f"    Z (上下): {bbox[:,2].min():.1f} ~ {bbox[:,2].max():.1f} cm")

    # ── 写入 FBX ─────────────────────────────────────────────
    print(f"\n[写入] {fbx_path}")
    write_fbx(
        all_verts   = ue5_verts,
        all_faces   = ue5_faces,
        all_normals = ue5_normals,
        all_colors  = all_colors,
        output_path = fbx_path,
        source_file = Path(glb_path).name,
    )
    size_mb = Path(fbx_path).stat().st_size / 1024 / 1024
    print(f"  文件大小: {size_mb:.2f} MB")

    return {
        "vertices":  len(ue5_verts),
        "triangles": len(ue5_faces),
        "output":    str(Path(fbx_path).resolve()),
        "size_mb":   round(size_mb, 2),
    }


def main():
    if hasattr(sys.stdout, "reconfigure"):
        try:
            sys.stdout.reconfigure(encoding="utf-8")
        except Exception:
            pass

    parser = argparse.ArgumentParser(description="GLB → UE5 FBX 转换器")
    parser.add_argument("input",  type=str, help="输入 .glb 文件路径")
    parser.add_argument("--out",  type=str, default=None,
                        help="输出 .fbx 路径（默认同名替换扩展名）")
    args = parser.parse_args()

    glb_path = args.input
    fbx_path = args.out or str(Path(glb_path).with_suffix(".fbx"))

    print("=" * 65)
    print("  GLB → UE5 FBX 转换器")
    print("=" * 65)
    print(f"  输入: {glb_path}")
    print(f"  输出: {fbx_path}")
    print(f"  坐标变换: GLTF Y-up 右手 → UE5 Z-up 左手")
    print(f"  单位换算: 1m (GLB) → 100cm (UE5)")

    result = convert(glb_path, fbx_path)

    print(f"\n{'='*65}")
    print(f"  转换完成")
    print(f"{'='*65}")
    print(f"  顶点数    : {result['vertices']:,}")
    print(f"  三角面数  : {result['triangles']:,}")
    print(f"  文件大小  : {result['size_mb']} MB")
    print(f"  输出路径  : {result['output']}")
    print()
    print("  UE5 导入设置建议:")
    print("    ✓ Import Uniform Scale  : 1.0  (已转换为厘米)")
    print("    ✓ Convert Scene         : 关闭 (坐标系已在文件中声明)")
    print("    ✓ Convert Scene Unit    : 关闭 (单位已转换)")
    print("    ✓ Generate Lightmap UVs : 建议开启")
    print("    ✓ Vertex Color Import   : Replace (保留顶点色)")


if __name__ == "__main__":
    main()
